# Generated by Django 5.0.3 on 2024-03-31 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaType',
            fields=[
                ('MTID', models.AutoField(primary_key=True, serialize=False)),
                ('MTName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('MID', models.AutoField(primary_key=True, serialize=False)),
                ('MName', models.CharField(max_length=255)),
                ('Plot', models.CharField(max_length=255)),
                ('Image', models.CharField(max_length=255)),
                ('Link', models.CharField(max_length=255)),
                ('Released_on', models.DateField()),
                ('Rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('Duration', models.IntegerField()),
                ('Year', models.IntegerField()),
                ('LID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflix.language')),
                ('MTID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflix.mediatype')),
            ],
        ),
        migrations.CreateModel(
            name='MediaGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflix.genre')),
                ('MID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflix.media')),
            ],
            options={
                'unique_together': {('MID', 'GID')},
            },
        ),
        migrations.CreateModel(
            name='ProfileWatchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflix.media')),
                ('PID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflix.profile')),
            ],
            options={
                'unique_together': {('PID', 'MID')},
            },
        ),
    ]
