# Generated by Django 5.0.3 on 2024-03-31 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0002_mediatype_media_mediagenre_profilewatchlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('SID', models.AutoField(primary_key=True, serialize=False)),
                ('SName', models.CharField(max_length=255)),
                ('Number', models.IntegerField()),
                ('MID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflix.media')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('EID', models.AutoField(primary_key=True, serialize=False)),
                ('EName', models.CharField(max_length=255)),
                ('Plot', models.TextField()),
                ('Number', models.IntegerField()),
                ('LID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflix.language')),
                ('SID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflix.season')),
            ],
        ),
    ]
