# Generated by Django 5.0.3 on 2024-04-18 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0003_season_episode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='Image',
            field=models.ImageField(upload_to='Media/'),
        ),
    ]
